apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-app
  labels:
    app: postgres
type: Opaque
data:
  # postgres (base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # your_jwt_secret_key_change_in_production (base64 encoded)
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9jaGFuZ2VfaW5fcHJvZHVjdGlvbg==
